<?php namespace Xiso\Homepage\Components;

use Cms\Classes\ComponentBase;
use Xiso\Homepage\Models\Info as NewInfo;
use Db;
use Illuminate\Database\Eloquent\Model;

class Info extends ComponentBase
{
    protected  $info;

    public  function componentDetails()
    {
        // TODO: Implement componentDetails() method.
        return[
            'name' => 'Info',
            'description' => ' Giới thiệu về  Xiso'
        ];
    }
    public  function onRun()
    {
        parent::onRun(); // TODO: Change the autogenerated stub
        $info = $this->info = $this->page['info'] = NewInfo::all()->take(3);
    }

    
}