<?php namespace Xiso\Homepage\Components;

use Cms\Classes\ComponentBase;
use Xiso\Homepage\Models\Teacher as NewTeacher;
use Db;
use Illuminate\Database\Eloquent\Model;
use Input;

class Teacher extends ComponentBase
{
    protected  $teacher;
    protected  $listteacher;

    public  function componentDetails()
    {
        // TODO: Implement componentDetails() method.
        return[
            'name' => 'Teacher',
            'description' => '  Thông tin giáo viên'
        ];
    }
    public  function onRun()
    {
        parent::onRun(); // TODO: Change the autogenerated stub
        $teacher = $this->teacher = NewTeacher::all()->take(10);
        $this->teacher = $this->page['teacher'] = $teacher;

    }
    public function onDatateacher()
    {   
        $id = Input::get('id');

        $listteacher =  NewTeacher::find($id);
        

        return response()->json($listteacher);
    }
}